---
name: grpc-poc
services:
  golang-server:
    build:
      dockerfile: Dockerfile
      context: .
      ssh:
        - default
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: sleep infinity
